version: '3.8'

services:
  goodiesdb-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goodiesdb-server
    ports:
      - "6379:6379"
    env_file:
      - .env.docker
    volumes:
      - goodiesdb-data:/app/data

volumes:
  goodiesdb-data:
